version: '3.7'

services:
  # Golang service
  cadana_app:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: cadana_app
    volumes:
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env 
    ports:
      - "8000:8000"
